version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: storemax-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: storemax
      MYSQL_USER: storemax
      MYSQL_PASSWORD: storemax123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
